"""
Builds src/data/questions.json for the Human-or-AI game from data.py.

Answers are derived HERE (at build time), never in the browser, so the
shipped JSON is the game's own data file. Run again whenever data.py changes.
"""
import importlib.util, json, re

BLOB = "https://opb2hisharlmxtua.public.blob.vercel-storage.com/"

spec = importlib.util.spec_from_file_location("d", "data.py")
m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)

DIFF_TO_LEVEL = {"easy": 1, "medium": 2, "hard": 3}

def is_ai(item):
    """Derive the boolean answer from the 'source' sentence, then cross-check
    against the ID pattern. Any disagreement is a hard error, not a guess."""
    s = item["source"].lower()
    ai_marker = "generated by ai" in s
    human_marker = ("written by human" in s or s.startswith("real")
                    or "real news" in s or "real human" in s)
    if ai_marker == human_marker:
        raise ValueError(f"Ambiguous source for {item['id']}: {item['source']!r}")
    verdict = ai_marker
    # cross-check with the id (e.g. EZ-TXT-AI-01 / EZ-TXT-HUMAN-01)
    up = item["id"].upper()
    if "-AI-" in up and not verdict:
        raise ValueError(f"ID says AI but source says human: {item['id']}")
    if "-HUMAN-" in up and verdict:
        raise ValueError(f"ID says HUMAN but source says AI: {item['id']}")
    return verdict

def make_content(item):
    """Text items keep their text. Image/video use the public blob URL."""
    if item["content_type"] == "text":
        return item["content"]
    return BLOB + item["content"].lstrip("/")

def make_tag(item):
    """Short uppercase label for the evidence chip, e.g. 'EASY - IMAGE'."""
    return f"{item['difficulty'].upper()} \u00b7 {item['content_type'].upper()}"

def make_explanation(item):
    """Reveal text: the explanation plus the strongest key points, so players
    learn a concrete, repeatable tell rather than a vague verdict."""
    parts = [item["explanation"].strip()]
    kp = item.get("key_points") or []
    if kp:
        bullets = "\n".join("\u2022 " + k.strip() for k in kp[:5])
        parts.append("What to look for:\n" + bullets)
    src = item.get("source", "").strip()
    if src:
        parts.append("Source: " + src)
    return "\n\n".join(parts)

out = []
for item in m.all_items:
    ai = is_ai(item)
    out.append({
        "id": item["id"],
        "content": make_content(item),
        "contentType": item["content_type"],       # text | image | video
        "isAI": ai,
        "category": item["content_type"].capitalize(),
        "topic": item["topic"],
        "tag": make_tag(item),
        "explanation": make_explanation(item),
        "levels": [DIFF_TO_LEVEL[item["difficulty"]], 4],  # 4 = Detective Mode (all)
        "difficulty": item["difficulty"],
    })

with open("questions.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=2)

# ---- report ----
from collections import Counter
print("Wrote questions.json with", len(out), "items")
print("AI vs Human:", Counter(i["isAI"] for i in out))
for lvl in (1, 2, 3):
    sub = [i for i in out if lvl in i["levels"]]
    print(f"  level {lvl}: {len(sub)} items,",
          Counter(i['contentType'] for i in sub),
          "AI:", sum(1 for i in sub if i['isAI']))
